### PR TITLE
Use cargo bench

### PR DESCRIPTION
**Pull request by garryod**
Uses cargo bench to perform benchmarking. Not the prettiest, would be nice to be able to run without a gui.

### CODE REVIEW

**Comment by gilesknap** [comment]
Thanks Garry this looks great. (but can't try it right now since I'm on a slow connection without any dev tools installed).

I did briefly look at bench but decided i needed nightly and was not sure if that was a great idea - now beginning to think there are other features  i want from nightly like serializers for traits.

re running with GUI - my perf test used to just run a fixed number of ticks with a fixed config that had consistent load - so i'll switch the test to do that again.

Cheers

**Comment by garryod** [comment]
I've ran nightly for a good number of my projects in the past and found it to be pretty stable so I personally don't tend to have reservations around it in that context. That'd be good, I couldn't quite figure out how to detach the two cleanly in the half hour I had

**Comment by gilesknap** [comment]
I made some changes to take the GUI out of the bench test see https://github.com/gilesknap/eyes2/commit/b2f7944df355bf0aad759e52531df21c402c6de7

Not sure if this is in the spirit of bench as I do multiple iterations of tick for one test. But this is what I want as I think there are mem cache concerns over multiple iterations - I get widely different perf on different processors.

**Comment by garryod** [comment]
`get_gettings` :rofl: can't believe I didn't catch that

Doesn't seem too unreasonable, though it's probably worth diving deeper into how to properly black-box the benchmarked code, [this RFC](https://rust-lang.github.io/rfcs/2360-bench-black-box.html) is worth a look

**Comment by gilesknap** [comment]
@garryod I just discovered `cargo flamegraph` and it's awesome.

**Pull request merged**
